// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fopatwvcfxtdlyvpwdgx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZvcGF0d3ZjZnh0ZGx5dnB3ZGd4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc3OTAyNDgsImV4cCI6MjA1MzM2NjI0OH0.YnOLF4SWJixQQDczAFBD90_Y0bNriR8p7ODPm4xh3us";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);